framework:
    secret: '%env(APP_SECRET)%'

    # needs to be disabled because we currently use a different translator with the same service name
    translator:
        enabled: false

    php_errors:
        log: true

    cache:
        app: cache.adapter.filesystem
        system: cache.adapter.filesystem

        pools:
            files:
                adapter: app.projectcache.provider
                default_lifetime: 2629743 # 1 month
            descriptors:
                adapter: app.projectcache.provider
                default_lifetime: 2629743 # 1 month

services:
    app.projectcache.provider:
        abstract: true
        class: phpDocumentor\Parser\Cache\FilesystemAdapter
        arguments:
            - 'phpdoc'
