framework:
    secret: '%env(APP_SECRET)%'

    # needs to be disabled because we currently use a different translator with the same service name
    translator:
        enabled: false

    php_errors:
        log: true

    cache:
        directory: '/tmp/phpdoc/pools'

        app: cache.adapter.filesystem
        system: cache.adapter.filesystem

        pools:
            files:
                adapter: cache.adapter.filesystem
            descriptors:
                adapter: cache.adapter.filesystem
