sudo: false

addons:
  apt:
    packages:
      - graphviz
  homebrew:
    packages:
      - graphviz

branches:
  except: /^(\S*)-nightly-(\S*)$/

matrix:
  fast_finish: true

stages:
  - test
  - windows
  - analysis

jobs:
  include:
    - stage: test
      language: php
      php:
        - 7.2
        - 7.3
      os: linux
      name: "Behat with phar"
      before_script:
        - travis_retry composer install --no-interaction --prefer-dist --optimize-autoloader
        - travis_retry composer global require phpunit/phpunit ^8 # cannot use phpunit.phar or require-dev, because this package is a phpunit dep
      script:
        - git tag v3.999.999
        - php bin/console cache:warmup --env=prod && php -d phar.readonly=false tools/box.phar compile
        - bin/behat -p phar
        - php build/phpDocumentor.phar run

    - stage: test
      language: php
      php:
        - 7.2
        - 7.3
      os: linux
      name: "php 7.2 Behat templates"
      before_script:
        - travis_retry composer install --no-interaction --prefer-dist --optimize-autoloader
        - travis_retry composer global require phpunit/phpunit ^6 # cannot use phpunit.phar or require-dev, because this package is a phpunit dep
      script:
        - mkdir -p /tmp/phpdoc-behat/clean_template/simple
        - bin/behat -p template

    - stage: windows
      language: sh
      os: windows
      before_install:
        - choco install php --version 7.2
        - export PATH=/c/tools/php72:$PATH
      script:
        - wget https://getcomposer.org/composer.phar
        - travis_retry php composer.phar install --no-interaction --prefer-dist --optimize-autoloader
        - travis_retry php composer.phar global require phpunit/phpunit ^6

    - stage: analysis
      language: php
      php:
        - 7.2
      os: linux
      name: "Phpunit code coverage"
      script:
        - $HOME/.composer/vendor/bin/phpunit
      after_script:
        - travis_retry wget --no-verbose https://phar.io/releases/phive.phar
        - travis_retry php phive.phar --no-progress install --trust-gpg-keys E82B2FB314E9906E php-coveralls/php-coveralls && ./tools/php-coveralls --verbose
        - travis_retry wget --no-verbose https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml

cache:
  directories:
  - $HOME/.composer
  - $HOME/.phive
  - ./docker

notifications:
  irc: "irc.freenode.org#phpdocumentor"
  slack:
    secure: "fjumM0h+4w3EYM4dpgqvpiCug7m4sSIC5+HATgwga/Nrc6IjlbWvGOv3JPgD3kQUhi18VmZfUYPmCv916SIbMnv8JWcrSaJXnPCgmxidvYkuzQDIw1HDJbVppGnkmwQA/qjIrM3sIEMfnu/arLRJQLI363aStZzGPxwIa4PDKcg="
  email:
  - me@mikevanriel.com
  - ashnazg@php.net
