language: php
php: [ 7.1, 7.2, 7.3 ]
sudo: false

branches:
except: /^(\S*)-nightly-(\S*)$/

matrix:
  fast_finish: true

install:
  - travis_retry composer install --no-interaction --prefer-dist --optimize-autoloader
before_script:
  - travis_retry composer global require phpunit/phpunit ^6 # cannot use phpunit.phar or require-dev, because this package is a phpunit dep
script:
  - $HOME/.composer/vendor/bin/phpunit --no-coverage
  - bin/behat -p default

jobs:
  include:

    - stage: test
      php: 7.1
      name: "php 7.1 Smoke test"
      before_script:
        - travis_retry sudo apt update
        - travis_retry sudo apt install graphviz
      script:
        - ./bin/phpdoc run

    - stage: test
      php: 7.2
      name: "Behat with phar"
      before_script:
        - travis_retry sudo apt update
        - travis_retry sudo apt install graphviz
      script:
        - git tag v3.999.999
        - php bin/console cache:warmup --env=prod && php -d phar.readonly=false tools/box.phar compile
        - bin/behat -p phar
        - php build/phpDocumentor.phar run

    - stage: test
      php: 7.1
      name: "php 7.1 Behat templates"
      script:
        - mkdir -p /tmp/phpdoc-behat/clean_template/simple
        - bin/behat -p template

    - stage: analysis
      php: 7.1
      name: "Phpunit code coverage"
      script:
        - $HOME/.composer/vendor/bin/phpunit
      after_script:
        - travis_retry wget --no-verbose https://phar.io/releases/phive.phar
        - travis_retry php phive.phar --no-progress install --trust-gpg-keys E82B2FB314E9906E php-coveralls/php-coveralls && ./tools/php-coveralls --verbose
        - travis_retry wget --no-verbose https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml

cache:
  directories:
  - $HOME/.composer
  - $HOME/.phive
  - ./docker

notifications:
  irc: "irc.freenode.org#phpdocumentor"
  slack:
    secure: "fjumM0h+4w3EYM4dpgqvpiCug7m4sSIC5+HATgwga/Nrc6IjlbWvGOv3JPgD3kQUhi18VmZfUYPmCv916SIbMnv8JWcrSaJXnPCgmxidvYkuzQDIw1HDJbVppGnkmwQA/qjIrM3sIEMfnu/arLRJQLI363aStZzGPxwIa4PDKcg="
  email:
  - me@mikevanriel.com
  - ashnazg@php.net
