language: php
php: [ 7.1, 7.2, nightly ]
sudo: false

branches:
except: /^(\S*)-nightly-(\S*)$/

env:

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_install: |
  if [[ "$TRAVIS_PULL_REQUEST_SLUG" == "" || "$TRAVIS_PULL_REQUEST_SLUG" == "$TRAVIS_REPO_SLUG" ]];then
    openssl aes-256-cbc -K $encrypted_f23adc84ec09_key -iv $encrypted_f23adc84ec09_iv -in .travis/secrets.tar.enc -out .travis/secrets.tar -d
    tar xvf .travis/secrets.tar -C .travis
  fi

install:
  - composer install --no-interaction --prefer-dist --optimize-autoloader
install:
  - travis_retry composer install --no-interaction --prefer-dist --optimize-autoloader
  - travis_retry composer global require phpunit/phpunit ^6 # cannot use phpunit.phar or require-dev, because this package is a phpunit dep
  - travis_retry wget --no-verbose https://phar.io/releases/phive.phar

script:
  - /home/travis/.composer/vendor/bin/phpunit --no-coverage
  - bin/behat -p default

jobs:
  include:
    - stage: dogfood
      php: 7.1
      script:
        - chmod u+x ./bin/phpdoc
        - ./bin/phpdoc run

    - stage: phar
      php: 7.1
      script:
        - php ./bin/console --env=prod cache:warm
        - php -d phar.readonly=false tools/box.phar compile
        - bin/behat -p phar
        - php build/phpDocumentor.phar run

    - stage: coverage
      php: 7.1
      script:
        - /home/travis/.composer/vendor/bin/phpunit
      after_script:
        - travis_retry php phive.phar --no-progress install --trust-gpg-keys E82B2FB314E9906E php-coveralls/php-coveralls && ./tools/php-coveralls --verbose
        - travis_retry wget --no-verbose https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml

    - stage: lint
      php: 7.1
      services:
        - docker
      before_script:
        - travis_retry php phive.phar --no-progress install --trust-gpg-keys 8E730BA25823D8B5 phpstan
      script:
        - ./tools/phpstan analyse src --level max --configuration phpstan.neon
        - docker-compose run --rm ecs

    - stage: release
      if: type IN (push)
      php: 7.1
      env:
        - VERSION=$(echo $TRAVIS_TAG | cut -c 2-10)
      script:
        - echo "${VERSION}" > VERSION
        - php ./bin/console --env=prod cache:warm
        - php -d phar.readonly=false tools/box.phar compile
        - openssl sha1 build/phpDocumentor.phar
        - echo "Update https://github.com/josegonzalez/homebrew-php/blob/master/Formula/phpdocumentor.rb with the latest version number and the SHA1 that is shown above with the path /get/phpDocumentor-${VERSION}.phar"
      deploy:
        provider: releases
        api_key:
          secure: WUchZXQQdIDtVQTYZsQ++2R1y6I+EzBrAACRuc33wAVd0mlqNmu3nb/c1Ou4pTk5JxjyGqm9Siyp9vobhBtzBh/hdXAnbZDWNx2l6R1M9S4R/Z/VbcQ+uIJ/VOoh2KvIOCcyVuFVmsemlVQCuatCRKswKmK/OuyQXy6ppyZMilA=
        file:
          - "build/phpDocumentor.phar"
          - "build/phpDocumentor.phar.pubkey"
        skip_cleanup: true
        on:
          repo: phpDocumentor/phpDocumentor2
          tags: true

    - stage: release
      if: type IN (push)
      php: 7.1
      env:
        - VERSION=$(echo $TRAVIS_TAG | cut -c 2-10)
      script:
        - echo "${VERSION}" > VERSION
        - git config --global user.email "builds@travis-ci.com"
        - git config --global user.name "Travis CI"
        - export GIT_TAG=$(git describe --tags --exclude="*nightly*" | sed -E "s/\-[a-z0-9]+\-/-nightly-/")
        - |
          if [ "${TRAVIS_TAG}" == "" ]; then
            git tag $GIT_TAG -a -m "Nightly build. Not a stable release. Expect bugs!";
            echo "${GIT_TAG}" > VERSION
          fi
        - php ./bin/console --env=prod cache:warm
        - php -d phar.readonly=false tools/box.phar compile
      deploy:
        provider: releases
        api_key:
          secure: WUchZXQQdIDtVQTYZsQ++2R1y6I+EzBrAACRuc33wAVd0mlqNmu3nb/c1Ou4pTk5JxjyGqm9Siyp9vobhBtzBh/hdXAnbZDWNx2l6R1M9S4R/Z/VbcQ+uIJ/VOoh2KvIOCcyVuFVmsemlVQCuatCRKswKmK/OuyQXy6ppyZMilA=
        file:
          - "build/phpDocumentor.phar"
          - "build/phpDocumentor.phar.pubkey"
        skip_cleanup: true
        on:
          repo: phpDocumentor/phpDocumentor2
          tags: false
          branch:
            - develop

cache:
  directories:
  - $HOME/.composer/cache/files
  - $HOME/.phive

notifications:
  irc: "irc.freenode.org#phpdocumentor"
  slack:
    secure: "fjumM0h+4w3EYM4dpgqvpiCug7m4sSIC5+HATgwga/Nrc6IjlbWvGOv3JPgD3kQUhi18VmZfUYPmCv916SIbMnv8JWcrSaJXnPCgmxidvYkuzQDIw1HDJbVppGnkmwQA/qjIrM3sIEMfnu/arLRJQLI363aStZzGPxwIa4PDKcg="
  email:
  - me@mikevanriel.com
  - ashnazg@php.net
