---
- name:  Clone clean repository into 'release' folder
  shell: git clone https://github.com/phpDocumentor/phpDocumentor2 release

- name: Install all dependencies using Composer
  shell: composer install -o --no-dev --prefer-dist -n
  args: { chdir: release }

- name: Increment version number and register number
  shell: versioner increment VERSION
  args: { chdir: release }

- name: Retrieve new version number
  shell: cat VERSION
  register: VERSION
  args: { chdir: release }

- name: Update master with develop branch
  shell: git $item
  with_items:
      - checkout master
      - merge develop
      - push origin master
  args: { chdir: release }

- name: Tag new version
  shell: git $item
  with_items:
      - tag v{{ VERSION.stdout }}
      - push origin --tags
  args: { chdir: release }

- name: Create PEAR package
  shell: phing deploy:package -Dversion.stability=stable
  args: { chdir: release }

- name: Move PEAR package to channel folder
  shell: mv phpDocumentor-{{ VERSION.stdout }}.tgz /var/www/pear.phpdoc.org/web/
  args: { chdir: release }

- name: Register new PEAR package with channel
  shell: ./pirum add web web/phpDocumentor-{{ VERSION.stdout }}.tgz
  args: { chdir: /var/www/pear.phpdoc.org }

- name: Create PHAR file
  shell: box build
  args: { chdir: release }

- name: Deploy phar to website
  shell: mv phpDocumentor.phar /var/www/phpdoc.org/web/phpDocumentor.phar
  args: { chdir: release }

- name: Archive new phar to archive folder
  shell: cp /var/www/phpdoc.org/web/phpDocumentor.phar /opt/artifacts/?/phpDocumentor-{{ VERSION.stdout }}.phar

