###################################################################################
## Guides - EXPERIMENTAL ##########################################################
###################################################################################

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  phpDocumentor\Guides\:
    resource: '../src/phpDocumentor/Guides/*'

  phpDocumentor\Guides\Handlers\:
    resource: '../src/phpDocumentor/Guides/Handlers/*Handler.php'
    tags: [{name: tactician.handler, typehints: true}]

  phpDocumentor\Pipeline\Stage\Parser\ParseGuides:
    tags:
      - { name: 'phpdoc.pipeline.api_documentation.parse', priority: 0 }

  phpDocumentor\Pipeline\Stage\Cache\LoadGuidesFromCache:
    tags:
      - { name: 'phpdoc.pipeline.api_documentation.parse', priority: 2000 }
      - { name: 'phpdoc.pipeline.api_documentation.transform', priority: 5000 }

  phpDocumentor\Pipeline\Stage\Cache\StoreGuidesToCache:
    tags:
      - { name: 'phpdoc.pipeline.api_documentation.parse', priority: -1000 }

  phpDocumentor\Guides\Handlers\ParseFileHandler:
    arguments:
      $parserStrategies: !tagged_iterator phpdoc.guides.parser.strategy
    tags: [{name: tactician.handler, typehints: true}]

  phpDocumentor\Guides\Handlers\RenderHandler:
    arguments:
      $references: !tagged_iterator phpdoc.guides.reference
    tags: [{name: tactician.handler, typehints: true}]
