services:
    phpdoc.application.pipeline:
      class: 'League\Pipeline\Pipeline'
      factory: ['phpDocumentor\Application\PipelineFactory', create]
      arguments: ['@phpDocumentor\Application\Stage\Configure']

    phpdoc.command.run.pipeline:
      class: 'League\Pipeline\Pipeline'
      factory: ['phpDocumentor\Application\PipelineFactory', create]
      arguments:
        - '@phpdoc.application.pipeline'
        - '@phpdoc.parse.pipeline.internal'
        - '@phpdoc.transform.pipeline.internal'

    phpdoc.command.parse.pipeline:
      class: 'League\Pipeline\Pipeline'
      factory: ['phpDocumentor\Application\PipelineFactory', create]
      arguments:
        - '@phpdoc.application.pipeline'
        - '@phpdoc.parse.pipeline.internal'

    phpdoc.parse.pipeline.internal:
      class: 'League\Pipeline\Pipeline'
      factory: ['phpDocumentor\Application\PipelineFactory', create]
      arguments:
        - '@phpDocumentor\Application\Stage\Parser\ConfigureCache'
        - '@phpDocumentor\Application\Stage\Parser'

    phpdoc.command.transform.pipeline:
      class: 'League\Pipeline\Pipeline'
      factory: ['phpDocumentor\Application\PipelineFactory', create]
      arguments:
        - '@phpdoc.application.pipeline'
        - '@phpdoc.transform.pipeline.internal'

    phpdoc.transform.pipeline.internal:
      class: 'League\Pipeline\Pipeline'
      factory: ['phpDocumentor\Application\PipelineFactory', create]
      arguments:
        - '@phpDocumentor\Application\Stage\Parser\ConfigureCache'
        - '@phpDocumentor\Application\Stage\Transform'
