imports:
  - { resource: 'pipelines.yaml' }
  - { resource: 'stages.yaml' }

parameters:
    locale: 'en'
    secret: ThisIsVerySecret!
    default_configuration_files:

    linker.substitutions:
      'phpDocumentor\Descriptor\ProjectDescriptor': ['files']
      'phpDocumentor\Descriptor\FileDescriptor':
          - 'tags'
          - 'classes'
          - 'interfaces'
          - 'traits'
          - 'functions'
          - 'constants'
      'phpDocumentor\Descriptor\ClassDescriptor':
          - 'tags'
          - 'parent'
          - 'interfaces'
          - 'constants'
          - 'properties'
          - 'methods'
          - 'usedTraits'
      'phpDocumentor\Descriptor\InterfaceDescriptor':
          - 'tags'
          - 'parent'
          - 'constants'
          - 'methods'
      'phpDocumentor\Descriptor\TraitDescriptor':
          - 'tags'
          - 'properties'
          - 'methods'
          - 'usedTraits'
      'phpDocumentor\Descriptor\FunctionDescriptor':
          - 'tags'
          - 'arguments'
      'phpDocumentor\Descriptor\MethodDescriptor':
          - 'tags'
          - 'arguments'
      'phpDocumentor\Descriptor\ArgumentDescriptor':
          - 'type'
      'phpDocumentor\Descriptor\PropertyDescriptor':
          - 'tags'
          - 'type'
      'phpDocumentor\Descriptor\ConstantDescriptor':
          - 'tags'
          - 'type'
      'phpDocumentor\Descriptor\Tag\ParamDescriptor': ['type']
      'phpDocumentor\Descriptor\Tag\ReturnDescriptor': ['type']
      'phpDocumentor\Descriptor\Tag\SeeDescriptor': ['reference']
      'phpDocumentor\Descriptor\Tag\UsesDescriptor': ['reference']
      'phpDocumentor\Descriptor\Type\CollectionDescriptor':
          - 'baseType'
          - 'type'
          - 'keyTypes'
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    ###################################################################################
    ## Autoloading definitions for whole namespaces ###################################
    ###################################################################################

#    phpDocumentor\:
#        resource: '../src/phpDocumentor/*'
#        exclude:
#          - '../src/phpDocumentor/**/Messages'
#          - '../src/phpDocumentor/Transformer/**/{Event, Exception}/{**, PathResolver.php}'

    phpDocumentor\Application\Console\:
      resource: '../src/phpDocumentor/Application/Console'

    phpDocumentor\Descriptor\:
        resource: '../src/phpDocumentor/Descriptor'

    phpDocumentor\Parser\Middleware\:
        resource: '../src/phpDocumentor/Parser/Middleware'
        tags: [ { name: 'phpdoc.parser.middleware', priority: 1000 } ]

    phpDocumentor\Transformer\:
      resource: '../src/phpDocumentor/Transformer'
      exclude: '../src/phpDocumentor/Transformer/**/{Event, Exception}/{**, PathResolver.php}'

    phpDocumentor\Infrastructure\:
      resource: '../src/phpDocumentor/Infrastructure'

    phpDocumentor\Compiler\:
      resource: '../src/phpDocumentor/Compiler'

    ###################################################################################
    ## Autoloading definitions for individual classes #################################
    ###################################################################################

    phpDocumentor\Application:
        public: true

    phpDocumentor\Application\Console\Command\Project\RunCommand:
        arguments: ['@phpDocumentor\Descriptor\ProjectDescriptorBuilder', '@phpdoc.command.run.pipeline']

    phpDocumentor\Application\Console\Command\Project\ParseCommand:
        arguments: ['@phpdoc.command.parse.pipeline', '@phpDocumentor\Translator\Translator']

    phpDocumentor\Application\Console\Command\Project\TransformCommand:
        arguments: ['@phpdoc.command.transform.pipeline']

    phpDocumentor\Descriptor\Builder\AssemblerFactory:
      class: 'phpDocumentor\Descriptor\Builder\AssemblerFactory'
      factory: ['phpDocumentor\Application\Builder\AssemblerFactoryFactory', create]

    phpDocumentor\Descriptor\Filter\Filter:
       calls:
        - [attachDefaults]


    phpDocumentor\Application\Parser\CacheFactory: ~
    phpDocumentor\Application\Parser\ProjectFactoryFactory: ~

    phpDocumentor\Configuration\Configuration:
      factory: ['@phpDocumentor\Configuration\ConfigurationFactory', 'fromDefaultLocations']

    phpDocumentor\Configuration\Factory\Version2:
        tags: [phpdoc.config_strategy]
    phpDocumentor\Configuration\Factory\Version3:
        arguments: ['data/xsd/phpdoc.xsd']
        tags: [phpdoc.config_strategy]
    phpDocumentor\Configuration\ConfigurationFactory:
        arguments:
          $strategies: !tagged phpdoc.config_strategy
          $defaultFiles:
            - "@=service('kernel').getWorkingDir() ~ '/phpdoc.xml'"
            - "@=service('kernel').getWorkingDir() ~ '/phpdoc.dist.xml'"
            - "@=service('kernel').getWorkingDir() ~ '/phpdoc.xml.dist'"

    phpDocumentor\Compiler\Linker\Linker:
      arguments: ['%linker.substitutions%']

    phpDocumentor\Compiler\Compiler:
      calls:
          - [insert, ['@phpDocumentor\Compiler\Pass\ElementsIndexBuilder', !php/const \phpDocumentor\Compiler\Pass\ElementsIndexBuilder::COMPILER_PRIORITY]]
          - [insert, ['@phpDocumentor\Compiler\Pass\MarkerFromTagsExtractor', !php/const \phpDocumentor\Compiler\Pass\MarkerFromTagsExtractor::COMPILER_PRIORITY]]
          - [insert, ['@phpDocumentor\Compiler\Pass\ExampleTagsEnricher', !php/const \phpDocumentor\Compiler\Pass\ExampleTagsEnricher::COMPILER_PRIORITY]]
          - [insert, ['@phpDocumentor\Compiler\Pass\PackageTreeBuilder', !php/const \phpDocumentor\Compiler\Pass\PackageTreeBuilder::COMPILER_PRIORITY]]
          - [insert, ['@phpDocumentor\Compiler\Pass\NamespaceTreeBuilder', !php/const \phpDocumentor\Compiler\Pass\NamespaceTreeBuilder::COMPILER_PRIORITY]]
          - [insert, ['@phpDocumentor\Compiler\Pass\ClassTreeBuilder', !php/const \phpDocumentor\Compiler\Pass\ClassTreeBuilder::COMPILER_PRIORITY]]
          - [insert, ['@phpDocumentor\Compiler\Pass\InterfaceTreeBuilder', !php/const \phpDocumentor\Compiler\Pass\InterfaceTreeBuilder::COMPILER_PRIORITY]]
          - [insert, ['@phpDocumentor\Compiler\Pass\ResolveInlineLinkAndSeeTags', !php/const \phpDocumentor\Compiler\Pass\ResolveInlineLinkAndSeeTags::COMPILER_PRIORITY]]
          - [insert, ['@phpDocumentor\Compiler\Pass\ResolveInlineMarkers', !php/const \phpDocumentor\Compiler\Pass\ResolveInlineMarkers::COMPILER_PRIORITY]]
          - [insert, ['@phpDocumentor\Compiler\Pass\Debug', !php/const \phpDocumentor\Compiler\Pass\Debug::COMPILER_PRIORITY]]
          - [insert, ['@phpDocumentor\Compiler\Linker\Linker', !php/const \phpDocumentor\Compiler\Linker\Linker::COMPILER_PRIORITY]]
          - [insert, ['@phpDocumentor\Transformer\Transformer', !php/const \phpDocumentor\Transformer\Transformer::COMPILER_PRIORITY]]

    phpDocumentor\Reflection\ProjectFactory:
       factory: 'phpDocumentor\Application\Parser\ProjectFactoryFactory:create'
       arguments: [!tagged phpdoc.parser.middleware]

    phpDocumentor\Parser\Parser:
      public: true
      lazy:  true

    phpDocumentor\Transformer\Router\Queue:
      calls:
        - [insert, ['@phpDocumentor\Transformer\Router\StandardRouter', 10000]]
        - [insert, ['@phpDocumentor\Transformer\Router\ExternalRouter', 10500]]

    phpDocumentor\Transformer\Template\PathResolver:
      class: 'phpDocumentor\Transformer\Template\PathResolver'
      arguments:
        - "@=service('phpDocumentor\\\\Application').templateDirectory()"

    phpDocumentor\Translator\Translator:
      public: true

    phpDocumentor\Reflection\DocBlock\ExampleFinder: ~

    phpDocumentor\Infrastructure\JmsSerializer\FileCache:
      arguments:
        ['%kernel.cache_dir%/jms_serializer']

    phpDocumentor\Transformer\Router\StandardRouter: ~

    phpDocumentor\Parser\Middleware\StopwatchMiddleware:
      tags: [ { name: 'phpdoc.parser.middleware', priority: 5000 } ]

    phpDocumentor\Parser\Middleware\CacheMiddleware:
      arguments:
        $dataStore: '@Stash\Pool'
      tags: [ { name: 'phpdoc.parser.middleware', priority: 4000 } ]

    phpDocumentor\Parser\Middleware\ErrorHandlingMiddleware:
      tags: [ { name: 'phpdoc.parser.middleware', priority: 3000 } ]

    phpDocumentor\Parser\Middleware\EmittingMiddleware:
      tags: [ { name: 'phpdoc.parser.middleware', priority: 0 } ]

    ###################################################################################
    ## Autoloading definitions for external services ##################################
    ###################################################################################

    Stash\Interfaces\PoolInterface: '@Stash\Pool'

    Stash\Pool:
      arguments: { $driver: '@Stash\Driver\FileSystem' }

    Stash\Driver\FileSystem:
      arguments: [ { path: 'build/api-cache' } ]

    League\Flysystem\MountManager: ~

    Zend\Cache\Storage\Adapter\Filesystem:
      class: Zend\Cache\Storage\Adapter\Filesystem
      factory: ['phpDocumentor\Infrastructure\Cache\ZendCacheFactory', create]

    Parsedown:
      class: Parsedown
      factory: ['Parsedown', 'instance']

    jms_serializer.metadata_factory:
        class: Metadata\MetadataFactory
        arguments: ['@jms_serializer.metadata.chain_driver', 'Metadata\ClassHierarchyMetadata', '%kernel.debug%']
        calls:
            - [setCache, ['@phpDocumentor\Infrastructure\JmsSerializer\FileCache']]

    ###################################################################################
    ## Service aliases for backwards compatibility ####################################
    ###################################################################################

    markdown:
      alias: Parsedown
      # used in a service provider so must be public
      public: true

    translator:
      alias: phpDocumentor\Translator\Translator
      # used in a service provider so must be public
      public: true

    transformer.routing.standard:
      alias: phpDocumentor\Transformer\Router\StandardRouter
      # used in a service provider so must be public
      public: true

    transformer.writer.collection:
      alias: phpDocumentor\Transformer\Writer\Collection
      # used in a service provider so must be public
      public: true

    descriptor.builder:
      alias: phpDocumentor\Descriptor\ProjectDescriptorBuilder
      # used in a service provider so must be public
      public: true

    Twig\Environment:
      # used in a service provider so must be public
      public: true

    Zend\Cache\Storage\StorageInterface: '@Zend\Cache\Storage\Adapter\Filesystem'
