parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false


#    phpDocumentor\:
#        resource: '../src/phpDocumentor/*'
#        exclude: '../src/phpDocumentor/**/Messages'

    phpDocumentor\Application:
        public: true

#    phpDocumentor\Application\Console\Command\Project\RunCommand:
#        factory: ['phpDocumentor\Application\Console\Command\Project\RunCommand', createInstance]
#        public: true
#        tags: [console.command]

    phpDocumentor\Descriptor\:
        resource: '../src/phpDocumentor/Descriptor'

#    phpDocumentor\Application\Stage\:
#        resource: '../src/phpDocumentor/Application/Stage'
#        exclude: '../src/phpDocumentor/Application/Stage/Configure'
#        public: true
#
#    phpDocumentor\Application\Configuration\:
#        resource: '../src/phpDocumentor/Application/Configuration'
#        public: true
