parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false


#    phpDocumentor\:
#        resource: '../src/phpDocumentor/*'
#        exclude: '../src/phpDocumentor/**/Messages'

    phpDocumentor\Application:
        public: true

    phpDocumentor\Application\Console\Command\Project\RunCommand:
        public: true

    phpDocumentor\Descriptor\:
        resource: '../src/phpDocumentor/Descriptor'
