on: [issues, pull_request]
name: Issue Triage
jobs:
  add-new-issues-to-project-column:
    runs-on: ubuntu-latest
    steps:
      - name: add-new-issues-to-organization-based-project-column
        uses: docker://takanabe/github-actions-automate-projects:v0.0.1
        if: github.event_name == 'issues' && github.event.action == 'opened'
        env:
          GITHUB_TOKEN: ${{ secrets.ISSUE_TRIAGE }}
          GITHUB_PROJECT_URL: https://github.com/orgs/phpDocumentor/projects/4
          GITHUB_PROJECT_COLUMN_NAME: Needs triage
      - name: add-new-prs-to-repository-based-project-column
        uses: docker://takanabe/github-actions-automate-projects:v0.0.1
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        env:
          GITHUB_TOKEN: ${{ secrets.ISSUE_TRIAGE }}
          GITHUB_PROJECT_URL: https://github.com/orgs/phpDocumentor/projects/4
          GITHUB_PROJECT_COLUMN_NAME: Needs triage
      - name: move-labeled-issues-to-todo-column
        uses: docker://takanabe/github-actions-automate-projects:v0.0.1
        if: github.event_name == 'issues' && github.event.action == 'labeled'
        env:
          GITHUB_TOKEN: ${{ secrets.ISSUE_TRIAGE }}
          GITHUB_PROJECT_URL: https://github.com/orgs/phpDocumentor/projects/4
          GITHUB_PROJECT_COLUMN_NAME: To Do
