on: status
name: Ci status
jobs:
  ci-status-update:
    runs-on: ubuntu-latest
    steps:
      - uses: 8398a7/action-slack@v2
        with:
          status: ${{ github.event.state }}
          icon_emoji: ':octocat:'
          channel: '#ci'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # required
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
